export const queryKeys = {
  authSession: () => ["auth", "session"] as const,
  categories: () => ["categories"] as const,
  certificates: () => ["certificates"] as const,
  chapters: (courseId: string) => ["chapters", courseId] as const,
  faqs: (courseId: string) => ["faqs", courseId] as const,
  faqsPublic: (courseId: string) => ["faqs", "public", courseId] as const,
  coupons: () => ["coupons"] as const,
  couponCheck: (code: string, courseId: string) => ["coupons", "check", code, courseId] as const,
  courses: (params?: Record<string, string | number>) =>
    params ? (["courses", params] as const) : (["courses"] as const),
  coursesManage: (params?: Record<string, string | number>) =>
    params ? (["courses", "manage", params] as const) : (["courses", "manage"] as const),
  courseById: (id: string) => ["courses", id] as const,
  courseStudy: (id: string) => ["courses", id, "study"] as const,
  courseLanding: (slug: string) => ["courses", "landing", slug] as const,
  dashboardAdmin: () => ["dashboard", "admin"] as const,
  dashboardTutor: () => ["dashboard", "tutor"] as const,
  dashboardUser: () => ["dashboard", "user"] as const,
  discussions: (lessonId: string) => ["discussions", lessonId] as const,
  discussionReplies: (id: string) => ["discussions", "replies", id] as const,
  // Bare "discussions" prefix — matches both discussions() and
  // discussionReplies() keys above for a broad post-mutation invalidation,
  // not a specific query's cache key.
  discussionsAll: () => ["discussions"] as const,
  enrollments: (params: { courseId?: string; userId?: string }) => ["enrollments", params] as const,
  // Bare "enrollments" prefix, same broad-invalidation role as discussionsAll above.
  enrollmentsAll: () => ["enrollments"] as const,
  feedbacks: () => ["feedbacks"] as const,
  feedbacksPinned: () => ["feedbacks", "pinned"] as const,
  lessons: (chapterId: string) => ["lessons", chapterId] as const,
  lessonContent: (id: string) => ["lessons", id, "content"] as const,
  lessonResources: (id: string) => ["lessons", id, "resources"] as const,
  studyLessonContent: (id: string) => ["lessons", id, "study-content"] as const,
  studyLessonResources: (id: string) => ["lessons", id, "study-resources"] as const,
  me: () => ["me"] as const,
  coursesEnrolled: () => ["courses", "enrolled"] as const,
  notes: (lessonId: string) => ["notes", lessonId] as const,
  notificationsFeed: () => ["notifications", "feed", "page"] as const,
  notificationsFeedBell: () => ["notifications", "feed", "bell"] as const,
  logsFeed: () => ["logs", "feed"] as const,
  securityFeed: (eventType?: string) =>
    eventType ? (["security", "events", eventType] as const) : (["security", "events"] as const),
  securityStats: () => ["security", "stats"] as const,
  monitoring: () => ["monitoring"] as const,
  health: () => ["health"] as const,
  profileTutor: () => ["profile", "tutor"] as const,
  profileUser: () => ["profile", "user"] as const,
  profilesAdmin: (params?: Record<string, string | number>) =>
    params ? (["profile", "admin", params] as const) : (["profile", "admin"] as const),
  quizMetadata: (lessonId: string) => ["quiz", "metadata", lessonId] as const,
  quizQuestions: (quizId: string) => ["quiz", "questions", quizId] as const,
  quizAttempts: (quizId: string) => ["quiz", "attempts", quizId] as const,
  quizAttemptDetail: (attemptId: string) => ["quiz", "attempts", "detail", attemptId] as const,
  transactions: () => ["transactions"] as const,
  transactionsCheckout: (courseId: string) => ["transactions", "checkout", courseId] as const,
  transactionStatus: (id: string) => ["transactions", "status", id] as const,
  updates: () => ["updates"] as const,
  updateFeed: (params?: Record<string, string | number>) =>
    params ? (["updates", "feed", params] as const) : (["updates", "feed"] as const),
  users: (params?: Record<string, string | number>) =>
    params ? (["users", params] as const) : (["users"] as const),
  roles: () => ["roles"] as const,
  permissions: () => ["permissions"] as const,
  wishlist: () => ["wishlist"] as const,
};
