package generic

// RBAC permission machine keys
const (
	PermAdminCategoriesManage    = "admin:categories:manage"
	PermAdminCoursesInspect      = "admin:courses:inspect"
	PermAdminDiscussionRead      = "admin:discussion:read"
	PermAdminDiscussionWrite     = "admin:discussion:write"
	PermAdminDiscussionDelete    = "admin:discussion:delete"
	PermAdminEnrollmentsInspect  = "admin:enrollments:inspect"
	PermAdminCouponsManage       = "admin:coupons:manage"
	PermAdminUpdatesManage       = "admin:updates:manage"
	PermAdminFeedbackInspect     = "admin:feedback:inspect"
	PermAdminTransactionsReadAll = "admin:transactions:read_all"
	PermAdminUsersList           = "admin:users:list"
	PermAdminUsersRoleAssign     = "admin:users:role:assign"
	PermAdminUsersRoleRevoke     = "admin:users:role:revoke"
	PermAdminUsersCreate         = "admin:users:create"
	PermAdminUsersRead           = "admin:users:read"
	PermAdminRolesCreate         = "admin:roles:create"
	PermAdminRolesRead           = "admin:roles:read"
	PermAdminRolesUpdate         = "admin:roles:update"
	PermAdminRolesDelete         = "admin:roles:delete"
	PermAdminRolesAssign         = "admin:roles:assign"
	PermAdminProfile             = "admin:profile"
	PermAdminRevokeCourse        = "admin:revoke:course"
	PermTutorCoursesManage       = "tutor:courses:manage"
	PermTutorDiscussionRead      = "tutor:discussion:read"
	PermTutorDiscussionWrite     = "tutor:discussion:write"
	PermTutorDiscussionDelete    = "tutor:discussion:delete"
	PermTutorFeedbackManage      = "tutor:feedback:manage"
	PermTutorQuizManage          = "tutor:quiz:manage"
	PermTutorUpdatesManage       = "tutor:updates:manage"
	PermTutorCouponsManage       = "tutor:coupons:manage"
)
