DROP TABLE IF EXISTS "profiles";
DROP TABLE IF EXISTS "twoFactors";
DROP TABLE IF EXISTS "jwkss";
DROP TABLE IF EXISTS "verifications";
DROP TABLE IF EXISTS "accounts";
DROP TABLE IF EXISTS "sessions";
DROP TABLE IF EXISTS "users";
