-- 003_courses.sql: Seed 10 Full Courses

INSERT INTO courses (
    id, tutor_id, slug, title, short_description, long_description,
    image_url, preview_video_url, language, level, actual_price, final_price,
    benefits, requirements, category_id, coupon_allowed,
    total_lectures, total_duration_seconds, rating_avg, feedback_count, status
) VALUES
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'tutor@example.com'),
        'go-golang-microservices-masterclass',
        'Go (Golang) Production Microservices Masterclass',
        'Build high-performance, fault-tolerant Go microservices using Fiber, gRPC, Postgres, and Docker.',
        'Master modern Go backend engineering from scratch to production. You will learn idiomatic Go pattern designs, Fiber web framework, gRPC streaming, SQL database pooling with sqlx, Redis caching, JWT auth, and containerization.',
        'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'advanced', 129.99, 49.99,
        ARRAY['Build production Go microservices', 'Master Fiber & gRPC', 'Implement SQL connection pooling', 'Deploy with Docker & Kubernetes'],
        ARRAY['Basic programming fundamentals', 'Familiarity with SQL concept'],
        (SELECT id FROM categories WHERE name = 'Golang & Backend'), true,
        25, 18000, 4.90, 18, 'published'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'john.doe@example.com'),
        'fullstack-nextjs-react-mastery',
        'Full-Stack Development with Next.js 15 & React 19',
        'Build fast, SEO-optimized web applications with Next.js 15 App Router, React Server Components, and Tailwind CSS.',
        'Learn the latest Next.js 15 features including React Server Components (RSC), Server Actions, Parallel & Intercepting Routes, Turbopack, and full authentication integration.',
        'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'intermediate', 149.99, 59.99,
        ARRAY['Next.js 15 App Router', 'React 19 Server Components', 'Tailwind CSS v4 Styling', 'Full-stack Authentication & Postgres integration'],
        ARRAY['JavaScript / TypeScript basics', 'HTML and CSS fundamentals'],
        (SELECT id FROM categories WHERE name = 'React & Next.js'), true,
        25, 21600, 4.85, 24, 'published'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'tutor@example.com'),
        'system-design-distributed-systems',
        'System Design & Distributed Systems Engineering',
        'Learn how to design scalable system architectures, load balancers, database sharding, and fault-tolerant message queues.',
        'An in-depth practical guide to passing system design interviews and architecting real-world web scale systems. Covers CAP theorem, consistent hashing, distributed caching, rate limiting, and event-driven architecture.',
        'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'advanced', 199.99, 79.99,
        ARRAY['Master System Design Principles', 'Architect High Availability Systems', 'Database Sharding & Replication', 'Event-Driven Microservices with Kafka'],
        ARRAY['2+ years software engineering experience', 'Understanding of basic network protocols'],
        (SELECT id FROM categories WHERE name = 'AWS & Cloud Architecture'), true,
        25, 25200, 4.95, 32, 'published'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'tutor@example.com'),
        'docker-kubernetes-modern-devops',
        'Docker, Kubernetes & Modern DevOps Pipeline',
        'Containerize applications, orchestrate Kubernetes clusters, and automate CI/CD pipelines from scratch.',
        'Become a DevOps expert. Learn container virtualization with Docker, multi-container compose setups, Kubernetes deployments, Helm charts, ingress controllers, and automated GitHub Actions workflows.',
        'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'intermediate', 119.99, 39.99,
        ARRAY['Docker image optimization', 'Kubernetes cluster deployment', 'Helm release management', 'Automated CI/CD with GitHub Actions'],
        ARRAY['Basic Linux command line usage'],
        (SELECT id FROM categories WHERE name = 'Docker & Kubernetes'), true,
        25, 19800, 4.80, 15, 'published'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'sarah.smith@example.com'),
        'python-data-science-machine-learning-bootcamp',
        'Python Data Science & Machine Learning Bootcamp',
        'Master NumPy, Pandas, Matplotlib, Scikit-Learn, and build real-world ML prediction models.',
        'Comprehensive data science course covering data analysis, cleaning, visualization, statistical inference, regression, classification models, random forests, and gradient boosting.',
        'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'beginner', 139.99, 44.99,
        ARRAY['Data wrangling with Pandas', 'Machine Learning algorithms with Scikit-Learn', 'Data visualization techniques', 'Statistical modeling'],
        ARRAY['No prior coding required; basic math helpful'],
        (SELECT id FROM categories WHERE name = 'Machine Learning with Python'), true,
        25, 23400, 4.92, 40, 'published'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'sarah.smith@example.com'),
        'deep-learning-llms-transformers-python',
        'Deep Learning, PyTorch & Large Language Models (LLMs)',
        'Build neural networks, PyTorch transformers, fine-tune LLMs, and deploy AI APIs.',
        'Dive deep into modern Artificial Intelligence. Understand artificial neural networks, convolutional networks (CNNs), transformers, self-attention mechanisms, and fine-tuning open-source LLMs (Llama 3, Mistral) with PyTorch.',
        'https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'advanced', 179.99, 69.99,
        ARRAY['Neural Networks in PyTorch', 'Transformer Architecture from Scratch', 'LLM Fine-tuning (LoRA / QLoRA)', 'Deploying AI Models to Production'],
        ARRAY['Python programming experience', 'Basic linear algebra and calculus concepts'],
        (SELECT id FROM categories WHERE name = 'Deep Learning & LLMs'), true,
        25, 27000, 4.98, 28, 'published'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'john.doe@example.com'),
        'flutter-dart-multiplatform-mobile-dev',
        'Flutter & Dart: Build Multi-Platform Mobile Apps',
        'Build iOS and Android applications with a single codebase using Flutter and Dart.',
        'Complete guide to mobile app development using Flutter. Master state management (Riverpod / Provider), REST API integration, native device capabilities, clean architecture, and App Store publishing.',
        'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'beginner', 129.99, 49.99,
        ARRAY['Build iOS and Android apps from 1 codebase', 'State management with Riverpod', 'Custom animations & UI themes', 'Publish to Google Play & Apple App Store'],
        ARRAY['Basic OOP programming concepts'],
        (SELECT id FROM categories WHERE name = 'Flutter & Dart'), true,
        25, 20500, 4.75, 19, 'published'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'john.doe@example.com'),
        'figma-ui-ux-design-system-mastery',
        'Figma to Code: UI/UX Design & System Engineering',
        'Design beautiful user interfaces, create design systems in Figma, and convert mockups to responsive frontend code.',
        'Learn user experience (UX) research, wireframing, interactive prototyping in Figma, typography, auto-layout, design token setup, and translation into clean HTML/Tailwind CSS.',
        'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'beginner', 99.99, 29.99,
        ARRAY['Master Figma Auto-Layout 5.0', 'Create Scalable Design Systems', 'UX Research & Wireframing', 'Export Design Tokens to Code'],
        ARRAY['No prior design software experience required'],
        (SELECT id FROM categories WHERE name = 'Figma & Prototyping'), true,
        25, 16200, 4.88, 22, 'published'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'tutor@example.com'),
        'rust-systems-programming-masterclass',
        'Rust Programming: Zero to Systems Master',
        'Build blazingly fast systems, web servers, and CLI utilities with Rust memory safety principles.',
        'Comprehensive Rust course covering ownership, borrowing, lifetimes, pattern matching, async runtime (Tokio), web services (Axum), and WebAssembly (Wasm).',
        'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'intermediate', 159.99, 54.99,
        ARRAY['Rust Memory Ownership & Lifetimes', 'Async I/O with Tokio', 'High Performance Web APIs with Axum', 'WebAssembly (Wasm) integration'],
        ARRAY['Familiarity with C, C++, Go, or Java'],
        (SELECT id FROM categories WHERE name = 'Golang & Backend'), true,
        25, 24000, 4.93, 26, 'published'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'john.doe@example.com'),
        'vue-nuxt3-modern-web-apps',
        'Vue 3 & Nuxt 3 Full-Stack Web Development',
        'Build fast, SSR & SSG web applications with Vue 3 Composition API, Pinia, and Nuxt 3.',
        'Explore the Vue 3 ecosystem. Learn reactive state management with Pinia, server-side rendering with Nuxt 3, TypeScript integration, and Tailwind CSS styling.',
        'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'intermediate', 119.99, 34.99,
        ARRAY['Vue 3 Composition API', 'Nuxt 3 Server-Side Rendering', 'Pinia State Management', 'TypeScript & Tailwind CSS integration'],
        ARRAY['Basic HTML, CSS, JavaScript'],
        (SELECT id FROM categories WHERE name = 'Vue & Nuxt'), true,
        25, 17500, 4.82, 16, 'published'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'rahulcode2026@gmail.com'),
        'kubernetes-gitops-cilium-mastery',
        'Kubernetes Platform Engineering: Cilium, ArgoCD & GitOps',
        'Master cloud native platform engineering with Cilium eBPF, ArgoCD declarative GitOps, Helm, and zero-trust service mesh.',
        'Take your Kubernetes engineering to staff level. In this course, Rahul Verma guides you through replacing kube-proxy with Cilium eBPF, implementing continuous delivery via ArgoCD GitOps, securing workloads with Kyverno policies, and telemetry with Hubble.',
        'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'advanced', 159.99, 59.99,
        ARRAY['Cilium eBPF CNI & Service Mesh', 'ArgoCD declarative GitOps automation', 'Kubernetes Zero-Trust Security Policies', 'Hubble network observability'],
        ARRAY['Strong Linux fundamentals', 'Familiarity with basic Docker & Kubernetes pods'],
        (SELECT id FROM categories WHERE name = 'Docker & Kubernetes'), true,
        15, 12600, 4.96, 21, 'published'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'tutor@example.com'),
        'git-github-essential-crash-course',
        'Git & GitHub Essential Crash Course: Zero to Collaboration Hero',
        'Learn essential Git version control, GitHub workflows, branching strategies, rebasing, and open source pull requests.',
        'A comprehensive free course to master Git commands, interactive rebasing, merge conflict resolution, pull request etiquette, and GitHub Actions basics.',
        'https://images.unsplash.com/photo-1556075798-4825dfaaf498?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'beginner', 0.00, 0.00,
        ARRAY['Master git branch, merge, and rebase', 'Collaborate via GitHub Pull Requests', 'Resolve tricky merge conflicts', 'Automate tests with GitHub Actions'],
        ARRAY['No prior experience required!'],
        (SELECT id FROM categories WHERE name = 'Golang & Backend'), false,
        10, 7200, 4.92, 54, 'published'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'tutor@example.com'),
        'ethical-hacking-network-penetration-testing',
        'Practical Ethical Hacking & Network Penetration Testing',
        'Learn real-world penetration testing, network vulnerability scanning, Wireshark packet analysis, and OWASP Top 10 exploits.',
        'Hands-on ethical hacking fundamentals. Master Kali Linux tools, Nmap reconnaissance, Metasploit exploitation, Burp Suite web assessment, and defensible security auditing.',
        'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'intermediate', 139.99, 49.99,
        ARRAY['Network scanning with Nmap', 'Web vulnerability exploitation with Burp Suite', 'Packet analysis using Wireshark', 'OWASP Top 10 mitigation strategies'],
        ARRAY['Basic networking knowledge (IP, TCP/UDP, DNS)'],
        (SELECT id FROM categories WHERE name = 'Ethical Hacking & Pentesting'), true,
        15, 14400, 4.87, 19, 'published'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'rahulcode2026@gmail.com'),
        'k8s-production-troubleshooting-draft',
        'Kubernetes Production Troubleshooting & Incident Response',
        'Debug CrashLoopBackOff, OOMKilled pods, DNS resolution failures, and etcd split-brain incidents under pressure.',
        'Work in progress course designed for SREs and DevOps engineers. Currently being prepared by Rahul Verma.',
        'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'advanced', 99.99, 39.99,
        ARRAY['Debug crash loop backoff errors', 'Resolve Kubernetes CoreDNS outages', 'Triage etcd performance bottlenecks'],
        ARRAY['Experience running Kubernetes clusters'],
        (SELECT id FROM categories WHERE name = 'Docker & Kubernetes'), true,
        5, 3600, 0.00, 0, 'draft'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'john.doe@example.com'),
        'legacy-angularjs-modern-migration-archived',
        'Legacy AngularJS to Modern React 19 Migration Patterns',
        'Strategic step-by-step techniques to modernize monolithic AngularJS 1.x codebases to modern React 19 and Next.js.',
        'Archived course preserved for reference on legacy modernization strategies and hybrid ng-react architectures.',
        'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'intermediate', 79.99, 29.99,
        ARRAY['Strangler Fig Pattern for frontend migrations', 'Interoperability between Angular directives and React components'],
        ARRAY['Knowledge of JavaScript and AngularJS'],
        (SELECT id FROM categories WHERE name = 'React & Next.js'), false,
        10, 7200, 4.50, 8, 'archived'
    ),
    (
        gen_random_uuid(),
        (SELECT id FROM users WHERE email = 'sarah.smith@example.com'),
        'python-ai-agents-langchain-langgraph',
        'AI Agents & Multi-Agent Systems with LangChain & LangGraph',
        'Build autonomous LLM agents, persistent memory workflows, human-in-the-loop validation, and RAG pipelines.',
        'Step beyond simple prompting. Learn how to architect stateful multi-agent systems using LangGraph, connect tools and external APIs, implement vector search with PgVector, and deploy production agent services.',
        'https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'English', 'intermediate', 189.99, 74.99,
        ARRAY['LangGraph cyclic workflows & state graphs', 'Tool calling and autonomous agent loops', 'PgVector semantic search integration', 'Production observability with LangSmith'],
        ARRAY['Intermediate Python skills', 'Basic understanding of LLMs'],
        (SELECT id FROM categories WHERE name = 'AI Agents & LLMOps'), true,
        15, 15000, 4.95, 33, 'published'
    )
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, final_price = EXCLUDED.final_price;

-- Set is_free flag for free courses
UPDATE courses SET is_free = true WHERE actual_price = 0 AND final_price = 0;

-- Seed Course FAQs
INSERT INTO faqs (id, course_id, question, answer, sort_order)
SELECT gen_random_uuid(), c.id, v.question, v.answer, v.sort_order
FROM (VALUES
    ('go-golang-microservices-masterclass', 'Do I need prior experience with Go to take this course?', 'Basic familiarity with programming syntax in any language (Go, Python, C, Java) is helpful, but we cover Go concurrency and fundamentals thoroughly from the beginning.', 1),
    ('go-golang-microservices-masterclass', 'Are the microservice projects deployed to real cloud servers?', 'Yes! We configure Docker containers, setup Postgres connection pooling with sqlx, and deploy to Kubernetes with continuous deployment pipelines.', 2),
    ('go-golang-microservices-masterclass', 'Do I get access to full source code repositories?', 'Yes, complete GitHub repositories for every single chapter with branch-by-branch checkpoints are included.', 3),
    ('fullstack-nextjs-react-mastery', 'Does this course cover Next.js 15 and React 19 Server Actions?', 'Yes, the entire curriculum was built from scratch specifically for Next.js 15 App Router, React 19 Server Components, Server Actions, and Tailwind CSS v4.', 1),
    ('fullstack-nextjs-react-mastery', 'How is authentication handled in the course projects?', 'We use modern Better-Auth with session tokens, JWT plugins, role-based access control, and Postgres persistence.', 2),
    ('fullstack-nextjs-react-mastery', 'Are TypeScript types provided for all exercises?', 'Yes, 100% of the project codebase is strictly typed in TypeScript with zero any assertions.', 3),
    ('system-design-distributed-systems', 'Is this course suitable for senior system design interview prep?', 'Absolutely. It is modeled after real architecture interviews at Google, Meta, and Amazon, covering CAP theorem, distributed consensus (Raft), sharding, and caching.', 1),
    ('system-design-distributed-systems', 'Will there be architecture diagrams included?', 'Yes, high-resolution architectural schematics and sequence diagrams are attached to every single module.', 2),
    ('docker-kubernetes-modern-devops', 'Do I need a paid cloud account for Kubernetes labs?', 'No, all hands-on exercises are designed to run locally using Minikube or Kind, with optional EKS/GKE deployment guides.', 1),
    ('docker-kubernetes-modern-devops', 'Are Helm charts included in the repository?', 'Yes, complete production-ready Helm charts with values.yaml configurations for dev, staging, and production environments are provided.', 2),
    ('python-data-science-machine-learning-bootcamp', 'Will I build real machine learning models in this bootcamp?', 'Yes, you will build and evaluate linear regression, random forests, XGBoost classifiers, and neural networks using real industry datasets.', 1),
    ('deep-learning-llms-transformers-python', 'Do I need an expensive GPU to follow along?', 'Google Colab Free or Kaggle T4 GPUs are completely sufficient for all fine-tuning and PyTorch training notebooks in this course.', 1),
    ('kubernetes-gitops-cilium-mastery', 'What makes Cilium eBPF different from standard Kubernetes kube-proxy?', 'Cilium replaces iptables with eBPF in kernel space for ultra low-latency packet routing, transparent mTLS, and real-time observability via Hubble.', 1),
    ('kubernetes-gitops-cilium-mastery', 'Is ArgoCD sync automated in this course?', 'Yes, we set up declarative Application and ApplicationSet CRDs with automated PR preview environments.', 2),
    ('git-github-essential-crash-course', 'Is this course really completely free?', 'Yes! This course is 100% free forever for all CourseHunt students to learn modern Git version control.', 1),
    ('python-ai-agents-langchain-langgraph', 'Does this course teach cyclic graphs with LangGraph?', 'Yes, we teach stateful cyclic graphs with conditional edges, human-in-the-loop checkpoints, and tool call routers.', 1)
) AS v(slug, question, answer, sort_order)
JOIN courses c ON c.slug = v.slug
ON CONFLICT (id) DO NOTHING;

